"""
LLMDraftTerraformGenerator

DRAFT-only fallback for unsupported architecture patterns.

Used ONLY when:
- No approved deterministic pattern matches.
- TERRAFORM_LLM_DRAFT_FALLBACK_ENABLED=true.
- LLM_PROVIDER is not none.

Output is always marked as untrusted and requires human review.
Never auto-approved. Never becomes a deterministic pattern.
"""

from __future__ import annotations

import asyncio
import json
import logging
from pathlib import PurePosixPath

from app.llm.base import LLMProvider
from app.reasoning.reasoning_schema import TerraformReasoningResult
from app.services.architecture_normalizer import NormalizedArchitecture

from .draft_prompt import ALLOWED_OUTPUT_PATHS, SYSTEM_PROMPT, build_draft_prompt
from .draft_schema import LLMDraftFile, LLMDraftResult

logger = logging.getLogger(__name__)


def _validate_path(path: str) -> bool:
    """Return True if path is in the allowed set and safe (no .., no absolute)."""
    if not path or "\\" in path:
        return False
    try:
        pure = PurePosixPath(path)
    except Exception:
        return False
    if pure.is_absolute() or ".." in pure.parts:
        return False
    return path in ALLOWED_OUTPUT_PATHS


def _parse_draft(raw: str) -> LLMDraftResult:
    """Parse LLM JSON output into LLMDraftResult. Returns FAILED on error."""
    try:
        text = raw.strip()
        if text.startswith("```"):
            lines = text.splitlines()
            text = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])
        data = json.loads(text)
        raw_files = data.pop("files", [])
        result = LLMDraftResult(draft_status="SUCCESS", **data)
        valid_files: list[LLMDraftFile] = []
        rejected: list[str] = []
        for f in raw_files:
            if not isinstance(f, dict):
                continue
            path = str(f.get("path", ""))
            if _validate_path(path):
                valid_files.append(LLMDraftFile(path=path, content=str(f.get("content", ""))))
            else:
                rejected.append(path)
                logger.warning("LLM draft: rejected disallowed file path: %r", path)
        result.files = valid_files
        if rejected:
            result.warnings.append(
                f"The following file paths were rejected (not in allowed set): {rejected}"
            )
        return result
    except Exception as exc:
        logger.warning("Failed to parse LLM draft output: %s", exc)
        return LLMDraftResult(
            draft_status="FAILED",
            error=f"Draft parse error: {type(exc).__name__}",
            warnings=[f"LLM draft output could not be parsed: {type(exc).__name__}"],
        )


class LLMDraftTerraformGenerator:
    """
    Generates draft Terraform HCL for unsupported patterns via LLM.

    This generator is disabled by default (TERRAFORM_LLM_DRAFT_FALLBACK_ENABLED=false).
    Output is always DRAFT, untrusted, and requires human review.
    """

    def generate_draft(
        self,
        architecture: NormalizedArchitecture,
        reasoning: TerraformReasoningResult,
        llm: LLMProvider,
    ) -> LLMDraftResult:
        try:
            arch_json = (
                architecture.model_dump_json(indent=2)
                if hasattr(architecture, "model_dump_json")
                else "{}"
            )
            prompt = "\n\n".join([
                SYSTEM_PROMPT,
                build_draft_prompt(
                    arch_json,
                    reasoning.terraform_strategy_summary or "No strategy summary available.",
                    reasoning.unsupported_reasons,
                ),
            ])
            raw = asyncio.get_event_loop().run_until_complete(llm.complete(prompt))
            result = _parse_draft(raw)
            result.warnings.insert(
                0,
                "DRAFT: This Terraform was generated by an LLM for an unsupported pattern. "
                "It is NOT trusted and requires human review before use.",
            )
            return result
        except Exception as exc:
            logger.warning("LLM draft generation failed: %s", type(exc).__name__)
            return LLMDraftResult(
                draft_status="FAILED",
                error=f"LLM draft generation failed: {type(exc).__name__}",
                warnings=["LLM draft generation call failed. No draft files produced."],
            )
