from typing import Type, TypeVar
from pydantic import BaseModel
from .base import LLMProvider
from .gemini_provider import GeminiProvider
from .groq_provider import GroqProvider
from ..core.config import settings
from ..core.exceptions import ConfigurationError

T = TypeVar("T", bound=BaseModel)

class FakeLLMProvider(LLMProvider):
    async def generate_structured_output(
        self,
        system_prompt: str,
        user_prompt: str,
        response_schema: Type[T]
    ) -> T:
        # Return a dummy architecture for testing
        data = {
            "architecture_id": "fake-123",
            "status": "READY_FOR_REVIEW",
            "title": "Fake Architecture",
            "requirement_summary": {
                "business_goal": "Test goal",
                "application_type": "Web App",
                "environment": "development",
                "functional_requirements": ["Requirement 1"],
                "non_functional_requirements": ["Requirement 2"],
                "constraints": ["Constraint 1"]
            },
            "cloud": {
                "provider": "AWS",
                "region": "us-east-1",
                "region_rationale": "Default region"
            },
            "solution": "This is a fake solution generated by the FakeLLMProvider.",
            "resources": [
                {
                    "id": "test-s3",
                    "name": "Test S3 Bucket",
                    "provider_type": "aws_s3_bucket",
                    "category": "STORAGE",
                    "scope": "REGIONAL",
                    "purpose": "Store test assets",
                    "configuration": {"versioning": True},
                    "depends_on": []
                }
            ],
            "relationships": [],
            "decisions": []
        }
        return response_schema(**data)

def get_llm_provider() -> LLMProvider:
    if settings.LLM_PROVIDER == "gemini":
        if not settings.GEMINI_API_KEY:
            raise ConfigurationError("GEMINI_API_KEY is not set")
        return GeminiProvider(
            api_key=settings.GEMINI_API_KEY,
            model_name=settings.GEMINI_MODEL,
            temperature=settings.LLM_TEMPERATURE
        )
    elif settings.LLM_PROVIDER == "groq":
        if not settings.GROQ_API_KEY:
            raise ConfigurationError("GROQ_API_KEY is not set")
        return GroqProvider(
            api_key=settings.GROQ_API_KEY,
            model_name=settings.GROQ_MODEL,
            temperature=settings.LLM_TEMPERATURE
        )
    elif settings.LLM_PROVIDER == "fake":
        return FakeLLMProvider()
    else:
        raise ConfigurationError(f"Unsupported LLM provider: {settings.LLM_PROVIDER}")
