from typing import Type, TypeVar
from pydantic import BaseModel
from .base import LLMProvider
from .gemini_provider import GeminiProvider
from .groq_provider import GroqProvider
from ..core.config import settings
from ..core.exceptions import ConfigurationError

T = TypeVar("T", bound=BaseModel)

class FakeLLMProvider(LLMProvider):
    async def generate_structured_output(
        self,
        system_prompt: str,
        user_prompt: str,
        response_schema: Type[T]
    ) -> T:
        # Return a dummy architecture for testing
        data = {
            "architecture_id": "fake-123",
            "status": "READY_FOR_REVIEW",
            "title": "Fake Architecture",
            "requirement_summary": {
                "business_goal": "Test goal",
                "application_type": "Web App",
                "environment": "development",
                "functional_requirements": ["Requirement 1"],
                "non_functional_requirements": ["Requirement 2"],
                "constraints": ["Constraint 1"]
            },
            "cloud": {
                "provider": "AWS",
                "region": "us-east-1",
                "region_rationale": "Default region"
            },
            "solution": "This is a fake solution generated by the FakeLLMProvider.",
            "resources": [
                {
                    "id": "app-alb",
                    "name": "Application Load Balancer",
                    "provider_type": "aws_lb",
                    "category": "LOAD_BALANCING",
                    "scope": "PUBLIC",
                    "purpose": "Route inbound traffic to the application service.",
                    "configuration": {"versioning": True},
                    "depends_on": []
                },
                {
                    "id": "platform-service",
                    "name": "Platform Backend Service",
                    "provider_type": "aws_ecs_service",
                    "category": "CONTAINER",
                    "scope": "PRIVATE",
                    "purpose": "Run the primary backend application containers.",
                    "configuration": {"desired_count": 1},
                    "depends_on": ["app-alb"]
                },
                {
                    "id": "nat-gw",
                    "name": "NAT Gateway",
                    "provider_type": "aws_nat_gateway",
                    "category": "NETWORK",
                    "scope": "PUBLIC_SUBNET",
                    "purpose": "Provide outbound internet access for private workloads.",
                    "configuration": {},
                    "depends_on": []
                },
                {
                    "id": "app-db",
                    "name": "Shared PostgreSQL RDS",
                    "provider_type": "aws_db_instance",
                    "category": "DATABASE",
                    "scope": "PRIVATE",
                    "purpose": "Store relational application data.",
                    "configuration": {"engine": "postgres"},
                    "depends_on": []
                },
                {
                    "id": "db-secret",
                    "name": "Secrets Manager",
                    "provider_type": "aws_secretsmanager_secret",
                    "category": "SECURITY",
                    "scope": "REGIONAL",
                    "purpose": "Store database credentials securely.",
                    "configuration": {},
                    "depends_on": []
                }
            ],
            "relationships": [
                {
                    "source_id": "app-alb",
                    "target_id": "platform-service",
                    "relationship_type": "ROUTES_TRAFFIC_TO",
                    "label": "routes traffic to",
                },
                {
                    "source_id": "platform-service",
                    "target_id": "app-db",
                    "relationship_type": "READS_FROM",
                    "label": "reads and writes",
                },
                {
                    "source_id": "platform-service",
                    "target_id": "db-secret",
                    "relationship_type": "AUTHENTICATES_WITH",
                    "label": "retrieves credentials",
                },
            ],
            "decisions": [
                {
                    "title": "Compute Choice",
                    "decision": "Use ECS Fargate for the application service.",
                    "rationale": "This keeps operations light for development while preserving a production-aligned container workflow.",
                    "alternatives_considered": [
                        {
                            "option": "Single EC2 instance",
                            "advantages": ["Lower raw compute cost"],
                            "disadvantages": ["More manual maintenance"],
                            "reason_not_selected": "It is cheaper, but it moves too much operational work onto the team.",
                        }
                    ],
                }
            ],
            "security_considerations": [
                "The database is kept off the public internet.",
            ],
            "reliability_considerations": [
                "The managed database reduces operational recovery work.",
            ],
            "scalability_considerations": [
                "The ECS service can scale out later if traffic grows.",
            ],
            "assumptions": [
                "This is a low-traffic development environment.",
            ],
            "cost_profile": {
                "profile": "LOW_COST_DEVELOPMENT",
                "estimated_level": "LOW_TO_MEDIUM",
                "main_cost_drivers": [
                    {
                        "resource_id": "nat-gw",
                        "reason": "NAT Gateway improves private networking but can become a noticeable cost driver in development.",
                    }
                ],
                "cost_saving_choices": [
                    "Single ALB shared by all backend services.",
                    "Fargate desired count set to 1 for development.",
                ],
                "cheaper_alternatives": [
                    {
                        "option": "Single EC2 instance running all containers",
                        "tradeoff": "Cheaper for development, but more manual operations and less scaling flexibility.",
                    }
                ],
                "production_upgrade_notes": [
                    "Use Multi-AZ RDS.",
                    "Add autoscaling policies.",
                ],
            },
        }
        return response_schema(**data)

def get_llm_provider() -> LLMProvider:
    if settings.LLM_PROVIDER == "gemini":
        if not settings.GEMINI_API_KEY:
            raise ConfigurationError("GEMINI_API_KEY is not set")
        return GeminiProvider(
            api_key=settings.GEMINI_API_KEY,
            model_name=settings.GEMINI_MODEL,
            temperature=settings.LLM_TEMPERATURE
        )
    elif settings.LLM_PROVIDER == "groq":
        if not settings.GROQ_API_KEY:
            raise ConfigurationError("GROQ_API_KEY is not set")
        return GroqProvider(
            api_key=settings.GROQ_API_KEY,
            model_name=settings.GROQ_MODEL,
            temperature=settings.LLM_TEMPERATURE
        )
    elif settings.LLM_PROVIDER == "fake":
        return FakeLLMProvider()
    else:
        raise ConfigurationError(f"Unsupported LLM provider: {settings.LLM_PROVIDER}")
